### ISSUE TITLE
Internal Server Error when publishing config files

### ISSUE THREAD

**Issue by garynewe** [f5devcentral/nginx-one-ga-lab#27]
(Option 2) Create a Config Sync Group for NGINX OSS
Editing the nginx.conf file as instructed
Created the /conf.d/default.conf file
edited as instructed
When I click on publish, I get an Internal Server Error
![Screenshot 2024-08-30 at 2 59 50 PM](https://github.com/user-attachments/assets/3995018e-e46b-49fe-8a29-c09b3342d768)

Event time was 2 59 50 PM Pacific.

I exited and when back in, and the config changes were there and seemed to be ok. I tried to publish again, but I received the same error.
I exited the NGINX One console, back to XC and then opened it again, in case there was an auth timeout, but the issue persisted.

I continued with the lab, deployed the OSS instances and the tests were passed successfully so the config was synced.

After the instances were deployed and the config sync status was green, I tried to publish again, and it seemed to work without issue. I made some changes to the files, and it seemed to work ok now.

**Comment by aknot242** [comment]
Thank you for reporting this. Apparently, this is a console issue and it has been reported internally. I believe a fix in the works.

**Comment by aknot242** [comment]
Update: This hasn't been fixed in the console yet, so I put a temporary note in the lab guide about this issue.

**Comment by aknot242** [comment]
This has been fixed. Note: you will need to delete any Config Sync Groups what were created during the period when this bug existed in the NGINX One Console.
