### ISSUE TITLE
Incorrect IP in API Check for Docker lab

### ISSUE THREAD

**Issue by garynewe** [f5devcentral/nginx-one-ga-lab#28]
NGINX Docker (Optional)
Step 11 - API Check
![Screenshot 2024-08-30 at 3 28 21 PM](https://github.com/user-attachments/assets/32f2dce9-9a09-4f88-84cc-d705cbf4ab58)

Instance is deployed, synced and running:

The lab-framework host has the correct IP address - 10.1.1.7/24
root@lab-framework:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: **ens5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 0a:bb:49:8b:72:79 brd ff:ff:ff:ff:ff:ff
    altname enp0s5
    inet 10.1.1.7/24 metric 100 brd 10.1.1.255 scope global dynamic ens5
       valid_lft 2774sec preferred_lft 2774sec
    inet6 fe80::8bb:49ff:fe8b:7279/64 scope link 
       valid_lft forever preferred_lft forever**
3: br-00ff0ede6f15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:4d:80:72:67 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-00ff0ede6f15
       valid_lft forever preferred_lft forever
    inet6 fe80::42:4dff:fe80:7267/64 scope link 
       valid_lft forever preferred_lft forever
4: **docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:b5:0e:c7:b5 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:b5ff:fe0e:c7b5/64 scope link 
       valid_lft forever preferred_lft forever_**
6: veth71d175c@if5: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-00ff0ede6f15 state UP group default 
    link/ether 42:23:03:79:a4:56 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::4023:3ff:fe79:a456/64 scope link 
       valid_lft forever preferred_lft forever
8: veth825a2dc@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-00ff0ede6f15 state UP group default 
    link/ether ba:96:11:84:18:c5 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::b896:11ff:fe84:18c5/64 scope link 
       valid_lft forever preferred_lft forever
10: vethe1e9bc6@if9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 5e:c1:e6:e9:ee:0e brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::5cc1:e6ff:fee9:ee0e/64 scope link 
       valid_lft forever preferred_lft forever
24: veth1dff4d7@if23: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether c6:53:bf:b2:1d:4e brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::c453:bfff:feb2:1d4e/64 scope link 
       valid_lft forever preferred_lft forever

But if I look at the container it is bound to a 172 address.
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "07b02bdf35889b782b99d1a9c620b55cfc73efca296f81ee820b7f17ee58c055",
            "SandboxKey": "/var/run/docker/netns/07b02bdf3588",
            "Ports": {
                "80/tcp": null
            },
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "148d8c8956f52f5de5cd75844a0f69ef8b9607cbcb4a1ae97dcf5b8b93e384e1",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            **"IPAddress": "172.17.0.3",**
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:03",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "MacAddress": "02:42:ac:11:00:03",
                    "DriverOpts": null,
                    "NetworkID": "319ee8672af367ba7fec2dc9857bbdb0dd756a2f8f703b139b9717ebf6d79a11",
                    "EndpointID": "148d8c8956f52f5de5cd75844a0f69ef8b9607cbcb4a1ae97dcf5b8b93e384e1",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": null
                }

So the check cannot work.

**Comment by aknot242** [comment]
That particular container is supposed to be mounted with a port mapping from 8080 (on the host) -> 80 (in the container). Did your docker run command include the `-p` parameter?

**Comment by garynewe** [comment]
Actually that was the issue, I copied the docker run command directly from the NGINX One console, as opposed from copying it from the lab guide specifically.
